# Generated by Django 5.0.2 on 2024-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='UserPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
