# Generated by Django 5.0.2 on 2024-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateur_userphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
    ]
