# Generated by Django 5.0.2 on 2024-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('dateHeure', models.DateTimeField()),
            ],
        ),
    ]
