# Generated by Django 5.0.2 on 2024-03-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0001_initial'),
        ('reservation', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.utilisateur'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='matricule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecin.medecin'),
        ),
    ]
