# Generated by Django 5.0.2 on 2024-05-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaireMedecin', '0002_horairemedecin_libre'),
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='HoraireMedecinID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horaireMedecin.horairemedecin'),
        ),
    ]
