# Generated by Django 5.0.2 on 2024-03-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horaire', '0002_remove_horaire_matricule'),
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireMedecin',
            fields=[
                ('HoraireMedecinID', models.AutoField(primary_key=True, serialize=False)),
                ('horaireID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horaire.horaire')),
                ('matricule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecin.medecin')),
            ],
        ),
    ]
