# Generated by Django 5.0.2 on 2024-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('specialite', models.CharField(max_length=25)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('cabinet', models.CharField(max_length=25)),
            ],
        ),
    ]
