# Generated by Django 5.0.2 on 2024-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='medecin_photos/'),
        ),
    ]
