# Generated by Django 5.0.2 on 2024-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0005_remove_medecin_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='Photo',
            field=models.ImageField(blank=True, default=None, upload_to='medecin_photos/'),
        ),
    ]
