# Generated by Django 5.0.2 on 2024-06-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0006_alter_medecin_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='prenom',
        ),
    ]
