# Generated by Django 5.0.2 on 2024-03-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('horaireID', models.AutoField(primary_key=True, serialize=False)),
                ('debMatin', models.CharField(max_length=5)),
                ('finMatin', models.CharField(max_length=5)),
                ('debAprem', models.CharField(max_length=5)),
                ('finAprem', models.CharField(max_length=5)),
                ('matricule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecin.medecin')),
            ],
        ),
    ]
