# Generated by Django 5.0.2 on 2024-03-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire',
            name='matricule',
        ),
    ]
