# Generated by Django 5.0.2 on 2024-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaire', '0002_remove_horaire_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire',
            name='debAprem',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='debMatin',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='finAprem',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='finMatin',
        ),
        migrations.AddField(
            model_name='horaire',
            name='debut',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horaire',
            name='fin',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horaire',
            name='jour',
            field=models.DateField(null=True),
        ),
    ]
