# Generated by Django 5.0.2 on 2024-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaire', '0005_alter_horaire_debut_alter_horaire_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='debut',
            field=models.DateTimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='fin',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
